config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweet.urls'))
]

tweet/urls.py
from django.urls import path, include
from tweet import views

app_name = "twitter"

urlpatterns = [
    path('', views.index, name="home"),
    path('search/', views.search, name="search"),
]

tweet/models.py
from django.db import models

class PersonModel(models.Model):
    username = models.CharField("ユーザーID", max_length=20)
    
    class Meta:
        db_table = "PersonModel"


class KeywordModel(models.Model):
    keyword = models.CharField("キーワード", max_length=30)
    since = models.CharField("いつから", max_length=10)
    until = models.CharField("いつまで", max_length=10)

    class Meta:
        db_table = "KeywordModel"

tweet/forms.py
from django import forms
from .models import PersonModel, KeywordModel


class PersonForm(forms.ModelForm):
    class Meta:     
        model = PersonModel
        fields = ["username"]

class KeywordForm(forms.ModelForm):
    class Meta:
        model = KeywordModel
        fields = ["keyword", "since", "until"]

tweet/views.py
from django.shortcuts import render
from tweet.forms import PersonForm, KeywordForm
from .application import person, keyword
import pandas as pd
import os

def index(request):
    form = PersonForm()
    context = {
        "form": form 
    }
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            person.main(username)

    return render(request, "tweet/index.html", context)

def search(request):
    form = KeywordForm()
    context = {
        'form': form
    }
    if request.method == "POST":
        form = KeywordForm(request.POST)
        if form.is_valid():
            keywords = request.POST.get("keyword")
            since = request.POST.get("since")
            until = request.POST.get("until")
            keyword.main(keywords, since, until)

    return render(request, "tweet/search.html", context)

templates/tweet/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>人物検索</title>
</head>
<body>
    <div>
        <form action="{%url 'twitter:home' %}" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="検索">
        </form>
    </div>
    <div>
        <a href="{% url 'twitter:search' %}">キーワード検索</a>
    </div>
</body>
</html>

templates/tweet/search.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>キーワード検索</title>
</head>
<body>
    <div>
        <form action="{% url 'twitter:search' %}" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="検索">
        </form> 
    </div>
    <div>
        <a href="{% url 'twitter:home' %}">人物検索</a>
    </div>
</body>
</html>